# **Faricha Aulia** ✨

In [3]:
import numpy as np
import math
from scipy import stats
import statistics as s
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# MEAN
print("Mean:")
apel = [100, 200, 150, 100, 120, 80, 90, 160, 110, 170]
avg_apel = sum(apel) / len(apel)
print(avg_apel)

# Median
print("\nMedian:")
def bubblesort(elements):
    for n in range(len(elements)-1, 0, -1):
        for i in range(n):
            if elements[i] > elements[i + 1]:
                elements[i], elements[i + 1] = elements[i + 1], elements[i]
    return elements

def calc_median(elements):
    elements = bubblesort(elements)
    len_elements = len(elements)
    if len_elements % 2 == 0:
        center = len_elements // 2
        return (elements[center-1] + elements[center]) / 2
    else:
        return elements[math.floor(len_elements / 2)]

apel = [100, 200, 150, 100, 120, 80, 90, 160, 110, 170]
median = calc_median(apel)
print(median)

# Mode
print("\nMode:")
nilai = [70, 80, 70, 70, 90, 100]

value_mode = stats.mode(nilai)
modus = s.mode(nilai)
print(modus)
print(value_mode)
print(value_mode.mode)

# Interquartile Range
print("\nInterquartile Range:")
data_baru = np.array([23, 56, 45, 65, 59, 55, 62, 54, 85, 25, 55])
print(pd.DataFrame(data_baru).describe())

# Normalization 1
print("\nNormalization 1:")
data_raw = np.array([
    [2, 3, 7, 30],
    [9, 4, 6, 1],
    [8, 15, 2, 40],
    [20, 10, 2, 6]
])
print(data_raw)

# Normalization 2
print("\nNormalization 2:")
data_raw = np.array([
    [2, 3, 7, 30],
    [9, 4, 6, 1],
    [8, 15, 2, 40],
    [20, 10, 2, 6]
])

scaler = MinMaxScaler()
data_scale = scaler.fit_transform(data_raw)
print(data_scale)

# Standardization
print("\nStandardization:")
data_raw = np.array([
    [2, 3, 7, 30],
    [9, 4, 6, 1],
    [8, 15, 2, 40],
    [20, 10, 2, 6]
])

scaler = StandardScaler()
data_stand = scaler.fit_transform(data_raw)
print(data_stand)

Mean:
128.0

Median:
115.0

Mode:
70
ModeResult(mode=70, count=3)
70

Interquartile Range:
               0
count  11.000000
mean   53.090909
std    17.466852
min    23.000000
25%    49.500000
50%    55.000000
75%    60.500000
max    85.000000

Normalization 1:
[[ 2  3  7 30]
 [ 9  4  6  1]
 [ 8 15  2 40]
 [20 10  2  6]]

Normalization 2:
[[0.         0.         1.         0.74358974]
 [0.38888889 0.08333333 0.8        0.        ]
 [0.33333333 1.         0.         1.        ]
 [1.         0.58333333 0.         0.12820513]]

Standardization:
[[-1.19319056 -1.03142125  1.20740686  0.66200869]
 [-0.11547005 -0.825137    0.76834982 -1.12387522]
 [-0.26943013  1.44398974 -0.98787834  1.27783073]
 [ 1.57809074  0.4125685  -0.98787834 -0.8159642 ]]
